import { Component, OnInit, inject, NgZone } from '@angular/core';
import { firstValueFrom } from 'rxjs';
import { CommonModule, NgIf, NgFor } from '@angular/common';
import { FormsModule, NgForm } from '@angular/forms'; // Import FormsModule
import { Producto } from '../../../models/producto'; // Corrected import path to '../../../models/producto'
import { ProductoService } from '../../services/producto.service';
import { AuthService } from '../../services/auth.service';
import { UploadService } from '../../services/upload.service';

@Component({
  selector: 'app-mantenimiento',
  standalone: true,
  imports: [
    CommonModule,
    NgIf,
    NgFor,
    FormsModule // Add FormsModule here for standalone components
  ],
  templateUrl: './mantenimiento.component.html',
  styleUrls: ['./mantenimiento.component.css']
})
export class MantenimientoComponent implements OnInit {
  private productoService = inject(ProductoService);
  private ngZone = inject(NgZone); // Inject NgZone
  private authService = inject(AuthService); // Inject AuthService to check current user
  private uploadService = inject(UploadService);

  productos: Producto[] = [];
  productoSeleccionado: Producto = { nombre: '', descripcion: '', categoria: '', tipo: '', foto: '' };
  isEditing: boolean = false;
  selectedProductId: string | null = null; // To store the ID of the product being edited

  // Properties for image upload
  imageUrlPreview: string | null = null;
  selectedFile: File | null = null;
  uploadProgress: number | null = null;
  isUploading: boolean = false;
  // Keep track of the existing image path when editing so we can delete/replace
  existingImagePath: string | null = null;

  ngOnInit(): void {
    this.cargarProductos();
  }

  cargarProductos(): void {
    this.productoService.getProducto().subscribe(data => {
      // Use NgZone to ensure updates are reflected in the UI
      this.ngZone.run(() => {
        this.productos = data;
      });
    });
  }

  onSubmit(): void {
    if (this.isEditing && this.selectedProductId) {
      this.actualizarProducto();
    } else {
      this.crearProducto();
    }
  }

  async crearProducto(): Promise<void> {
    try {
      // Upload image if a new file is selected
      if (this.selectedFile) {
        const currentUser = this.authService.getCurrentUser();
        if (!currentUser) {
          alert('Debes iniciar sesión para subir imágenes.');
          return; // Stop creation until user logs in
        }

        // Debugging: log current user and token to help diagnose 403s
        console.log('Uploading as user:', currentUser.uid);
        try {
          const token = await currentUser.getIdToken();
          console.log('Current user ID token (first 40 chars):', token?.substring(0, 40));
        } catch (tErr) {
          console.warn('Could not retrieve ID token before upload:', tErr);
        }

        const uploadResult = await this.uploadImage(this.selectedFile);
        this.productoSeleccionado.foto = uploadResult.downloadURL;
        this.productoSeleccionado.fotoPath = uploadResult.path;
      }

      const newProducto: Producto = {
        ...this.productoSeleccionado,
        // id will be generated by Firebase
      };

      await this.productoService.crearProducto(newProducto);
      this.resetForm();
      this.cargarProductos(); // Refresh the list
    } catch (error) {
      console.error("Error al crear producto:", error);
      // Handle error appropriately, e.g., show a message to the user
    }
  }

  async actualizarProducto(): Promise<void> {
    if (!this.selectedProductId) return;

    try {
      // Upload new image if selected, otherwise keep the existing one
      if (this.selectedFile) {
        // Fetch latest product data from Firestore to ensure we delete the currently-stored image
        try {
          const currentProducto = await firstValueFrom(this.productoService.getProductoRefPorId(this.selectedProductId));
          const currentPath = currentProducto?.fotoPath;
          if (currentPath) {
            try {
              await this.productoService.deleteFile(currentPath);
            } catch (err) {
              console.warn('Could not delete previous image from storage (continuing):', err);
            }
          }
        } catch (err) {
          console.warn('Could not read current product from Firestore before deleting image:', err);
        }

        const uploadResult = await this.uploadImage(this.selectedFile);
        this.productoSeleccionado.foto = uploadResult.downloadURL;
        this.productoSeleccionado.fotoPath = uploadResult.path;
      }

      const updatedProducto: Producto = {
        ...this.productoSeleccionado,
        id: this.selectedProductId // Ensure ID is included if needed by service, though updateDoc usually uses it in the doc path
      };

      await this.productoService.actualizarProducto(this.selectedProductId, updatedProducto);
      this.resetForm();
      this.cargarProductos(); // Refresh the list
    } catch (error) {
      console.error("Error al actualizar producto:", error);
      // Handle error appropriately
    }
  }

  editProduct(producto: Producto): void {
    this.isEditing = true;
    this.selectedProductId = producto.id || null; // Store the ID
    // Create a copy to avoid modifying the original object directly until save
    this.productoSeleccionado = { ...producto };
    // Set preview for existing image if available
    this.imageUrlPreview = producto.foto || null;
    this.existingImagePath = producto.fotoPath || null;
    this.selectedFile = null; // Clear selected file when editing
  }

  deleteProduct(id: string): void {
    if (confirm('¿Está seguro de que desea eliminar este producto?')) {
      this.productoService.eliminarProducto(id).then(() => {
        this.cargarProductos(); // Refresh the list
      }).catch(error => {
        console.error("Error al eliminar producto:", error);
        // Handle error appropriately
      });
    }
  }

  cancelEdit(): void {
    this.resetForm();
  }

  resetForm(): void {
    this.isEditing = false;
    this.selectedProductId = null;
    this.productoSeleccionado = { nombre: '', descripcion: '', categoria: '', tipo: '', foto: '' };
    this.imageUrlPreview = null; // Clear preview
    this.selectedFile = null; // Clear selected file
    // If using NgForm for validation reset:
    // this.productForm.resetForm(); // This requires productForm to be available via ViewChild or template reference
  }

  onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.selectedFile = input.files[0];
      const reader = new FileReader();
      reader.onload = (e) => {
        this.ngZone.run(() => {
          this.imageUrlPreview = e.target?.result as string;
        });
      };
      reader.readAsDataURL(this.selectedFile);

      // If editing, clear the existing photo URL as a new one will be uploaded
      if (this.isEditing) {
        this.productoSeleccionado.foto = '';
        // existingImagePath will be removed when uploading new image (handled in actualizarProducto)
      }
    } else {
      this.selectedFile = null;
      this.imageUrlPreview = null;
      // If editing and no new file is selected, retain the old photo
      if (this.isEditing && this.selectedProductId) {
        // Re-fetch the product to get its original photo, or store it elsewhere
        // For simplicity, let's assume the `productoSeleccionado` still holds the old photo if not cleared
        // If `productoSeleccionado.foto` was cleared above, we might need to re-assign it from a stored value
        // For now, if no file is selected, the existing `productoSeleccionado.foto` will be used by the service.
      }
    }
  }

  uploadImage(file: File): Promise<{ downloadURL: string; path: string }> {
    return new Promise((resolve, reject) => {
      this.isUploading = true;
      this.uploadService.uploadFile(file).subscribe({
        next: (upload) => {
          this.ngZone.run(() => {
            this.uploadProgress = upload.progress;
          });
          if (upload.downloadURL && upload.path) {
            this.isUploading = false;
            resolve({ downloadURL: upload.downloadURL, path: upload.path });
          }
        },
        error: (error) => {
          console.error('Upload failed:', error);
          this.isUploading = false;
          alert('La subida de la imagen falló. Por favor, inténtalo de nuevo.');
          reject(error);
        }
      });
    });
  }

  // Remove selected image before saving (used in the form)
  // Note: manual deletion of stored images was removed per request. If a new image
  // is uploaded when editing, the previous stored image is deleted automatically.
  removeSelectedImage(): void {
    // Simply clear the in-form selection and preview without touching stored image
    this.selectedFile = null;
    this.imageUrlPreview = null;
  }
}
